networks:
  student-transfer-dev:
    driver: bridge
services:
  studenttransfer.api:
    container_name: studenttransfer.api
    image: studenttransfer.api
    build:
      context: .
      dockerfile: StudentTransfer.Api/Dockerfile
    ports:
      - "8080:80"
  studenttransfer.db:
    container_name: studenttransfer.db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e6WRC(vPwCt94SNh
      POSTGRES_DB: student-transfer-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes: 
  postgres-data:
